name: Deploy PR to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Deploy to GH Pages
        run: |
          cd build
          git init
          git config user.name "GitHub Actions Deploy"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy PR#${{ github.event.pull_request.number }} [skip ci]" --allow-empty
          git push -f https://${{ github.actor }}:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
