name: Deploy PR Preview and Production

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  deploy-preview:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Create PR subdirectory
        run: |
          mkdir -p public/pr-${{ github.event.pull_request.number }}
          cp -r build/* public/pr-${{ github.event.pull_request.number }}/

      - name: Deploy PR Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Add Preview URL comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo
            const prNumber = context.payload.pull_request.number
            const previewUrl = `https://${repo.owner}.github.io/${repo.repo}/pr-${prNumber}/`

            await github.rest.issues.createComment({
              ...repo,
              issue_number: prNumber,
              body: `**Preview disponível:** [Acesse aqui](${previewUrl})\n\nEsta é uma prévia do seu PR. O link será válido até o PR ser fechado ou mesclado.`
            })

  deploy-production:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to Production
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: false

      - name: Find Related PRs and Notify
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo
            const productionUrl = `https://${repo.owner}.github.io/${repo.repo}/`

            // Busca PRs associados a este commit
            const prsResponse = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              ...repo,
              commit_sha: context.sha
            })

            // Notifica cada PR mesclado
            for (const pr of prsResponse.data) {
              if (pr.merged_at) {
                await github.rest.issues.createComment({
                  ...repo,
                  issue_number: pr.number,
                  body: `**Deploy em produção realizado!**\n\nSua alteração está agora disponível em: [${productionUrl}](${productionUrl})`
                })
                
                // Adiciona label ao PR
                try {
                  await github.rest.issues.addLabels({
                    ...repo,
                    issue_number: pr.number,
                    labels: ['deployed']
                  })
                } catch (error) {
                  console.log('Erro ao adicionar label:', error)
                }
              }
            }
