name: Deploy PR to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Deploy to GH Pages
        run: yarn run deploy-pr
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
