name: Deploy to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  deploy-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Set deployment subdir
        id: deploy-path
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "DEPLOY_SUBDIR=/pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_SUBDIR=/" >> $GITHUB_ENV
          fi

      - name: Build project
        run: yarn run build

      - name: Deploy PR to GH Pages (Subdirectory)
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          REPO="https://${{ github.actor }}:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git"
          SUBDIR="pr-${{ github.event.pull_request.number }}"

          git clone --branch gh-pages --single-branch $REPO gh-pages-tmp || \
            (mkdir -p gh-pages-tmp && cd gh-pages-tmp && git init && git checkout -b gh-pages)

          mkdir -p gh-pages-tmp/$SUBDIR
          rm -rf gh-pages-tmp/$SUBDIR/*
          cp -R build/* gh-pages-tmp/$SUBDIR/

          cd gh-pages-tmp
          git config user.name "GitHub Actions Deploy"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy PR#${{ github.event.pull_request.number }} to /$SUBDIR [skip ci]" --allow-empty
          git push -f $REPO gh-pages

      - name: Comment with Preview URL
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          COMMENT="Deploy disponível em: https://${OWNER}.github.io/${REPO_NAME}/pr-${PR_NUMBER}/"
          echo "Comentando na PR: $COMMENT"
          curl -s -H "Authorization: token $GH_PAGES_TOKEN" \
               -H "Content-Type: application/json" \
               -X POST \
               -d "{\"body\": \"$COMMENT\"}" \
               "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Deploy main to GH Pages root
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          REPO="https://${{ github.actor }}:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git"

          git clone --branch gh-pages --single-branch $REPO gh-pages-tmp || \
            (mkdir -p gh-pages-tmp && cd gh-pages-tmp && git init && git checkout -b gh-pages)

          rm -rf gh-pages-tmp/*
          cp -R build/* gh-pages-tmp/

          cd gh-pages-tmp
          git config user.name "GitHub Actions Deploy"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Deploy from main branch [skip ci]" --allow-empty
          git push -f $REPO gh-pages
